version: "3.9"

services:
  api:
    image: thirumuruganaks/prashiskshan-backend:latest
    container_name: prashiskshan-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - /home/ubuntu/prashiskshan-backend/.env
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
